# Copyright (c) 2022 - 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
spec:
  operand:
    image: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:v4.16
    image: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9@sha256:e49f59d6edc1c2175030de62be57eb8670e26c734dd33d178eb33a64c4fc3f2a
    imagePullPolicy: Always
    servicePort: 12000
  workerConfig:
    configData: |
