kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
    packages:
    - name: nfd
      channels:
      - name: stable
    - name: trustee-operator
      channels:
      - name: stable
    - name: sandboxed-containers-operator
      channels:
      - name: stable
    - name: cluster-observability-operator
      channels:
      - name: stable
    - name: compliance-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable-6.2
    - name: elasticsearch-operator
      channels:
      - name: stable-5.8
    - name: local-storage-operator
      channels:
      - name: stable
    - name: kiali-ossm
      channels:
      - name: stable
    - name: jaeger-operator
      channels:
      - name: stable
    - name: servicemeshoperator
      channels:
      - name: stable
