apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-cc
handler: kata-snp
overhead:
  podFixed:
    memory: "350Mi"
    cpu: "250m"
    sev-snp.amd.com/esids: 1
scheduling:
  nodeSelector:
     node-role.kubernetes.io/master: ""
