apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 96-kata-kernel-config
  namespace: openshift-machine-config-operator
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,$source
        mode: 420
        overwrite: true
        path: /etc/kata-containers/snp/config.d/96-kata-kernel-config
